# 代碼功能說明: DataLake SeaweedFS Master 服務暴露配置
# 創建日期: 2025-12-29
# 創建人: Daniel Chung
# 最後修改日期: 2025-12-29

apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-datalake-master
  namespace: seaweedfs-datalake
  labels:
    app: seaweedfs
    component: master
    project: datalake
spec:
  type: ClusterIP
  ports:
    - port: 9333
      targetPort: 9333
      protocol: TCP
      name: http
    - port: 19333
      targetPort: 19333
      protocol: TCP
      name: grpc
  selector:
    app: seaweedfs
    component: master
    project: datalake
