# 代碼功能說明: DataLake SeaweedFS Volume 服務暴露配置
# 創建日期: 2025-12-29
# 創建人: Daniel Chung
# 最後修改日期: 2025-12-29

apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-datalake-volume
  namespace: seaweedfs-datalake
  labels:
    app: seaweedfs
    component: volume
    project: datalake
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 18080
      targetPort: 18080
      protocol: TCP
      name: grpc
  selector:
    app: seaweedfs
    component: volume
    project: datalake
