# 代碼功能說明: ArangoDB Kubernetes PVC
# 創建日期: 2025-11-25 22:25 (UTC+8)
# 創建人: Daniel Chung
# 最後修改日期: 2025-11-25 22:25 (UTC+8)

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arangodb-data
  namespace: ai-box
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd
