# 代碼功能說明: ArangoDB Kubernetes Secret
# 創建日期: 2025-11-25 22:25 (UTC+8)
# 創建人: Daniel Chung
# 最後修改日期: 2025-11-25 22:25 (UTC+8)

apiVersion: v1
kind: Secret
metadata:
  name: arangodb-secret
  namespace: ai-box
type: Opaque
stringData:
  ARANGO_ROOT_PASSWORD: "ai_box_arangodb_password"
  ARANGO_USERNAME: "root"
  ARANGO_DATABASE: "ai_box_kg"
